export { VEHICLE_TABLE_HEAD, TABLE_STATUS_FILTERS, SIDEBAR_TABLE_HEAD } from './tableData'
export type { VehicleHeadElement, VehicleTableStatusFilter, SideBarHeadElement } from './types'
export { isVehicleStatus } from './types'
export { mapToTableData } from './mapToTableData'
export { statusFilterMapper } from './statusFilterMapper'
export { mapToList } from './mapToList'
export {statusToOption} from './statusToOption'
export { vehicleToMarkers } from './vehToMarkers.ts'